config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about', as: 'about'

  resources :entries 

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
  	@entries = Entry.all 
  end

  def show
  	@entry = Entry.find(params[:id])
  end

  def new
  	@entry = Entry.new 
  end
end
	
	def edit 
		@entry = Entry.find(params[:id])
	end 

	def update 
		entry = Entry.find(params[:id])
		if @entry.update(entry_params)
			redirect_to entries_path
		else
			render :edit 
	end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/entries/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @entry do |f| %>
	

app/views/entries/index.html.erb
<h1>Entries</h1>
<% @entries.each do |entry| %>
	<h2><%= entry.title %></h2>
	<p><%= entry.body %></p>
	<%= link_to 'Show Entry', entry_path(entry)%>
	<% end %>
	<% link_to 'Edit', edit_entry_path(entry) %>
	<% end %>

app/views/entries/new.html.erb
<h1>Entries#new</h1>
<p>Find me in app/views/entries/new.html.erb</p>

app/views/entries/show.html.erb
<h1>Entry</h1>
<h2><%= @entry.title %>
<p><%= @entry.body %></p>
<%= link_to 'Back', entries_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Entries', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>